//
//  NAAlertView.h
//  NAAlertView
//
//  Created by Jonathan Hooper on 7/26/13.
//  Copyright (c) 2013 NewAperio LLC. All rights reserved.
//

typedef NS_ENUM(NSInteger, NAAlertViewButtonType){
    NAAlertViewButtonTypeRegular = 0,
    NAAlertViewButtonTypeCancel = 1
};

#import <UIKit/UIKit.h>

@interface NAAlertView : UIView

/**
 The background color for the alert view. The default is white.
 */
@property (nonatomic, strong) UIColor *backgroundColor;

/**
 The border color for the alert view. Also the border color for the button borders and the color for text. The default is grey.
 */
@property (nonatomic, strong) UIColor *borderColor;

/**
 The font used for the text in the alert view.
 */
@property (nonatomic, strong) UIFont *font;


/**
 The title to display at the top of the alert view. This is required for the view to display.
 */
@property (nonatomic, strong) NSString *title;

/**
 The alert view's message. This is required for the view to display.
 */
@property (nonatomic, strong) NSString *message;

/**
 The image to be displayed by the alert view. This is not required to display the view.
 */
@property (nonatomic, strong) UIImage *image;

/**
 Changes the default background color for all alert views generated
 
 @param color The new default background color
 */
+ (void)setDefaultBackgroundColor:(UIColor *)color;

/**
 Changes the default border color for all alert view generated
 
 @param color The new default border color
 */
+ (void)setDefaultBorderColor:(UIColor *)color;

/**
 Sets the default font for all alert views generated
 
 @param font The new default font
 */
+ (void)setDefaultFont:(UIFont *)font;



/**
 Returns an empty NAAlertView object with just a greyed out background.
 The view generated by this method is not ready to be displayed. An alert view will not be displayed without at least a title and a message.
 
 @return A NAAlertView with just a greyed out background. This method does not draw the alert box.
 */
- (id)init;

/**
 Returns an empty NAAlertView object with just a greyed out background.
 This method just calls init. The frame provided is ignored since the view occupies the entire screen.
 The view generated by this method is not ready to be displayed. An alert view will not be displayed without at least a title and a message.
 
 @return A NAAlertView with just a greyed out background. This method does not draw the alert box.
 @see -init
 */
- (id)initWithFrame:(CGRect)frame;

/**
 Returns a NAAlertView with a title and message.
 
 @param title The title to be displayed by the alert view
 @param message The message to be displayed by the alert view
 @return A NAAlertView that is ready to be displayed with a title and message
 */
- (id)initWithTitle:(NSString *)title message:(NSString *)message;

/**
 Returns a NAAlertView with a title, message, and image.
 
 @param title The title to be displayed by the alert view
 @param message The message to be displayed by the alert view
 @param imagePath The image path of the image to be displayed by the alert view
 @return A NAAlertView that is ready to be displayed with a title, message, and image
 */
- (id)initWithTitle:(NSString *)title message:(NSString *)message imagePath:(NSString *)imagePath;

/**
 Returns a NAAlertView with a title, message, and image.
 
 @param title The title to be displayed by the alert view
 @param message The message to be displayed by the alert view
 @param imageName The name of the image in the main bundle to be displayed by the alert view
 @return A NAAlertView that is ready to be displayed with a title, message, and image
 */
- (id)initWithTitle:(NSString *)title message:(NSString *)message imageNamed:(NSString *)imageName;

/**
 Returns a NAAlertView with a title, message, and image.
 
 @param title The title to be displayed by the alert view
 @param message The message to be displayed by the alert view
 @param image The image to be displayed by the alert view
 @return A NAAlertView that is ready to be displayed with a title, message, and image
 */
- (id)initWithTitle:(NSString *)title message:(NSString *)message image:(UIImage *)image;



/**
 Adds a button to the alert view
 
 An alert view can only have two buttons. A cancel button and another tpye of button. Adding a button of type other than a `NAAlertViewButtonTypeCancel` will result in the existing button being overwritten.
 
 A regular button will be added on the left and and a cancel button will be added on the right.
 
 @param title The button's title
 @param block The block to be executed when the button is pressed
 @param buttonType The type of button to be selected
 @see NAAlertViewButtonType
 */
- (void)addButtonWithTitle:(NSString *)title block:(void (^)())block type:(NAAlertViewButtonType)buttonType;

/**
 Removes a button from the alert view
 
 @param buttonType The type of button that you wish to remove
 */
- (void)removeButtonWithType:(NAAlertViewButtonType)buttonType;



/**
 Displayes the alert view over the current view controller
 
 @param If yes, animates the appearance, otherwise does not.
 */
- (void)showAnimated:(BOOL)animated;
/**
 Removes the alert view from the current view controller
 
 @param If yes, animates the dismissal, otherwise does not.
 */
- (void)dismissAnimated:(BOOL)animated;

@end